---
apiVersion: gateway.envoyproxy.io/v1alpha1  # first, required
kind: BackendTrafficPolicy  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # required
  labels:  # required
    app: TODO  # first
    app.kubernetes.io/name: TODO  # required
spec:  # required
  targetRefs:
  - group: TODO  # first, required
    kind: TODO  # required
    name: TODO
  timeout:
    http:
      connectionIdleTimeout: TODO
      requestTimeout: TODO
  retry:
    numRetries: TODO
    perRetry:
      timeout: TODO
      backOff:
        baseInterval: TODO
        maxInterval: TODO
    retryOn:
      triggers: []
      httpStatusCodes: []
  rateLimit:
    local:
      rules:
      - clientSelectors:  # first
        - sourceCIDR:
            type: TODO  # first
            value: TODO
        limit:
          requests: TODO
          unit: TODO
  circuitBreaker:
    maxConnections: TODO
    maxPendingRequests: TODO
    maxParallelRequests: TODO
    maxParallelRetries: TODO
