---
apiVersion: cert-manager.io/v1  # first, required
kind: Certificate  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # required
  labels:  # required
    app: TODO  # first
    app.kubernetes.io/name: TODO  # required
  annotations: {}
spec:  # required
  dnsNames: []  # preferred
  issuerRef:  # preferred
    kind: TODO  # first, required
    name: TODO
  secretName: TODO  # preferred
