---
apiVersion: external-secrets.io/v1beta1  # first, required
kind: ClusterSecretStore  # required
metadata:  # required
  name: TODO  # first, required
  labels:  # required
    app: TODO  # first
    app.kubernetes.io/name: TODO  # required
  annotations: {}
spec:  # required
  controller: TODO  # first, required
  provider:  # required
    onepassword:  # required
      connectHost: TODO  # required
      vaults: {}  # required
      auth:  # required
        secretRef:  # required
          connectTokenSecretRef:  # required
            name: TODO  # first, required
            namespace: TODO  # required
            key: TODO  # required
