---
apiVersion: gateway.envoyproxy.io/v1alpha1  # first, required
kind: EnvoyProxy  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # required
  labels:  # required
    app: TODO  # first
    app.kubernetes.io/name: TODO  # required
  annotations: {}
spec:  # required
  provider:
    type: TODO  # first
    kubernetes:
      envoyService:
        annotations: {}
      envoyDeployment:
        strategy:
          type: TODO  # first
          rollingUpdate:
            maxSurge: TODO
            maxUnavailable: TODO
        pod:
          priorityClassName: TODO
          affinity: {}  # ditto=Pod.spec.affinity
        container:
          image: TODO  # first
          resources:
            requests:  # first
              cpu: TODO
              memory: TODO
            limits:
              cpu: TODO
              memory: TODO
      envoyHpa:
        minReplicas: TODO  # first
        maxReplicas: TODO
        metrics:
        - type: TODO  # first
          resource:
            name: TODO  # first
            target:
              type: TODO
              averageUtilization: TODO
  telemetry:
    accessLog:
      settings:
      - format:
          type: TODO  # first
          json: {}
        sinks:
        - type: TODO  # first
          file:
            path: TODO
  bootstrap:
    type: TODO  # first
    value: TODO
