---
apiVersion: external-secrets.io/v1beta1  # first, required
kind: ExternalSecret  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # preferred
  labels:  # required
    app: TODO  # first
    app.kubernetes.io/name: TODO  # required
  annotations: {}
spec:  # required
  secretStoreRef:  # first, required
    kind: TODO  # first, required
    name: TODO  # required
  target:  # required
    creationPolicy: TODO  # preferred
    template:  # required
      metadata:  # required
        labels:  # required
          app: TODO  # first
          app.kubernetes.io/name: TODO  # required
  data:  # required
  - secretKey: TODO  # first, required
    remoteRef:  # required
      key: TODO  # first, required
      property: TODO  # preferred
