---
apiVersion: gateway.networking.k8s.io/v1  # first, required
kind: HTTPRoute  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # required
  labels:  # required
    app: TODO  # first
    app.kubernetes.io/name: TODO  # required
  annotations: {}
spec:  # required
  hostnames: []  # first, required
  parentRefs:  # required
  - group: TODO  # first, preferred
    kind: TODO  # preferred
    name: TODO  # required
    namespace: TODO  # required
  rules:  # required
  - matches:  # first
    - path:  # required
        type: TODO  # required
        value: TODO  # required
    backendRefs:
    - group: TODO  # first, preferred
      kind: TODO  # preferred
      name: TODO  # required
      port: TODO  # required
  - filters:
    - type: TODO  # first, required
      requestRedirect:
        scheme: TODO
        statusCode: TODO
