---
apiVersion: batch/v1  # first, required
kind: Job  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # preferred
  labels:  # required
    app: TODO  # first
    app.kubernetes.io/name: TODO  # required
  annotations: {}
spec:  # required
  completions: TODO
  parallelism: TODO
  backoffLimit: TODO
  ttlSecondsAfterFinished: TODO
  template:  # required
    metadata:  # preferred
      name: TODO  # first
      labels:  # preferred
        app: TODO  # first
        app.kubernetes.io/name: TODO  # required
      annotations: {}
    spec:  # ditto=Pod.spec
