---
apiVersion: v1  # first, required
kind: PersistentVolumeClaim  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # preferred
  labels:  # required
    app: TODO  # first
    app.kubernetes.io/name: TODO  # required
  annotations: {}
spec:  # required
  storageClassName: TODO  # preferred
  accessModes: []
  resources:  # required
    requests:  # require
      storage: TODO  # required
